/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'user' at '10:42 26/01/16' with Gradle 2.10
 *
 * @author user, @date 10:42 26/01/16
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
