/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'user' at '10:42 26/01/16' with Gradle 2.10
 *
 * @author user, @date 10:42 26/01/16
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
